### ISSUE TITLE
button:active state not being respected

### ISSUE THREAD

**Issue by ericdfields** [imathis/fancy-buttons#12]
I've tried a few different ways to influence the border width on border:active, and I just can't get it to give. Try any of the :active properties below for example:

```
button
  +fancy-button-structure
  +fancy-button-colors($oBlue)
  +fancy-button-size(14px,4px,1px)
button:active
  border-width: 2px
  +fancy-button-size(14px,4px,2px)
```

**Comment by imathis** [comment]
I believe this is fixed in the latest version. If not try the pre release `gem install fancy-buttons --pre`
