### ISSUE TITLE
Error when starting server on Rails 3.0.3 and Ruby 1.9.2

### ISSUE THREAD

**Issue by jmdfm** [imathis/fancy-buttons#15]
I followed the install instructions and when I run 'rails s' I get the following error:

/Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/fancy-buttons-1.0.4/lib/fancy-buttons.rb:1:in `<top (required)>': uninitialized constant Object::Compass (NameError)
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/bundler-1.0.3/lib/bundler/runtime.rb:64:in`require'
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/bundler-1.0.3/lib/bundler/runtime.rb:64:in `block (2 levels) in require'
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/bundler-1.0.3/lib/bundler/runtime.rb:62:in`each'
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/bundler-1.0.3/lib/bundler/runtime.rb:62:in `block in require'
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/bundler-1.0.3/lib/bundler/runtime.rb:51:in`each'
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/bundler-1.0.3/lib/bundler/runtime.rb:51:in `require'
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/bundler-1.0.3/lib/bundler.rb:112:in`require'
    from /Users/johnmcdowall/Development/rails/Arifembi/config/application.rb:7:in `<top (required)>'
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/railties-3.0.3/lib/rails/commands.rb:28:in`require'
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/railties-3.0.3/lib/rails/commands.rb:28:in `block in <top (required)>'
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/railties-3.0.3/lib/rails/commands.rb:27:in`tap'
    from /Users/johnmcdowall/.rvm/gems/ruby-1.9.2-p0@rails/gems/railties-3.0.3/lib/rails/commands.rb:27:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by jmdfm** [comment]
And the solution is:

Double check that compass is before fancy-buttons in your Gemfile!

**Comment by chriseppstein** [comment]
lol

**Comment by jmdfm** [comment]
I am shame faced like a cat who's just fallen off a table.
