### ISSUE TITLE
File "button_bg.png" not copied to Rails public/images by default

### ISSUE THREAD

**Issue by cseeger** [imathis/fancy-buttons#16]
Not sure if this is isolated to my case specifically, but I noticed this after adding fancy-buttons to my Gemfile, running a bundle, then firing up IE7. 

Rails 3.0.0.rc with Compass already installed.

Of course, after copying the png from the gem, everything works as normal.

**Comment by cseeger** [comment]
"compass install -r fancy-buttons -f fancy-buttons" was not run. All working now, thanks!

**Comment by imathis** [comment]
Ah, glad you figured it out. Some plugins don't use assets, but those that do need to be installed in order to work.
