### ISSUE TITLE
Syntax error: Not a valid color stop: #6a6a6a 10%

### ISSUE THREAD

**Issue by ghost** [imathis/fancy-buttons#18]
Hi there, i'm getting the following error:

<pre><code>/* Syntax error: Not a valid color stop: #6a6a6a 10%
        on line 7 of /usr/local/rvm/gems/ruby-1.8.7-p330/gems/fancy-buttons-0.5.4/lib/stylesheets/_fancy-gradient.sass, in `linear-gradient'
        from line 7 of /usr/local/rvm/gems/ruby-1.8.7-p330/gems/fancy-buttons-0.5.4/lib/stylesheets/_fancy-gradient.sass, in `fancy-gradient'
        from line 78 of /usr/local/rvm/gems/ruby-1.8.7-p330/gems/fancy-buttons-0.5.4/lib/stylesheets/_fancy-buttons.sass, in `fb-state-colors'
        from line 68 of /usr/local/rvm/gems/ruby-1.8.7-p330/gems/fancy-buttons-0.5.4/lib/stylesheets/_fancy-buttons.sass, in `fb-color'
        from line 23 of /usr/local/rvm/gems/ruby-1.8.7-p330/gems/fancy-buttons-0.5.4/lib/stylesheets/_fancy-buttons.sass, in `fancy-button-colors'</code></pre>

I have tried version 0.5.4, 1.0.3 and 1.0.4, each with the same result.

**Comment by imathis** [comment]
Which versions of Compass and Sass are you using?

**Comment by ghost** [comment]
ah, got it... I used the sass/haml alpha versions. now reinstalled haml-3.0.25 and it works fine... 

just to let you know if maybe anyone runs into the same.

**Comment by imathis** [comment]
Thanks for the heads up. Compass 0.11 and Sass 3.1 will be released fairly soon and I'll be releasing an update that makes it compatible with them. I just haven't had time to tackle it yet what with the holidays and all.

**Comment by ghost** [comment]
no prob. you are doing a great job man. keep it going that way.

**Comment by davesmylie** [comment]
For anyone else getting this issue, I had to downgrade to compass (0.10.4), sass (3.1.0.alpha.216) and haml (3.0.25) to make the error go away.
