### ISSUE TITLE
"undefined operation" using compass-color mixins inside conditional

### ISSUE THREAD

**Issue by ghost** [imathis/fancy-buttons#2]
Seeing these error in a few places, and I don't know enough about Sass syntax to suggest a fix. I have the latest, greatest fancy-buttons + compass + compass-colors cloned from github.

Sass::SyntaxError on line ["33"] of /home/korch/opt/lib/ruby/gems/gems/fancy-buttons-0.3.2/lib/sass/./_fancy_buttons.sass: Undefined operation: "saturation(#444444) gt 0".

Sass::SyntaxError on line ["43"] of /home/korch/opt/lib/ruby/gems/gems/fancy-buttons-0.3.2/lib/sass/./_fancy_buttons.sass: Undefined operation: "luminosity(saturate(#444444, 40)) lt luminosity(#aaaaaa)".

**Comment by ghost** [comment]
whoops, didn't add 'require "compass-colors"' to my config/compass.config file, now it works!

**Comment by imathis** [comment]
Glad you figured that out. FYI soon this will be integrated into Sass core, so you won't have to require compass-colors. I'll probably be updating the gem in a week or two to support a new Haml/Sass and new Compass release.
