### ISSUE TITLE
validating fancy-buttons scss problems with browser specific attributes

### ISSUE THREAD

**Issue by bitcoiners** [imathis/fancy-buttons#23]
Hello, 
I imported fancy_buttons plugin from https://github.com/imathis/fancy-buttons 
and added 
@include fancy-button(#2966a8); 
to one of my mixins. when running compass validate I errors like this: 

Property -moz-border-radius doesn&#39;t exist : 

The compiled stylesheet has this code: 
input[type='submit'] { 
  -moz-border-radius: 6px; 
  -webkit-border-radius: 6px; 
  -o-border-radius: 6px; 
  -ms-border-radius: 6px; 
  -khtml-border-radius: 6px; 
  border-radius: 6px; 
  font-size: 18px; 
  line-height: 1.2em; 
  padding: 0.3em 1em; 
  border-width: 1px; 
  background-color: #0064d1; 
  background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, color- 
stop(0%, #94bbe5), color-stop(10%, #4b8cd3), color-stop(50%, #265f9c), 
color-stop(50%, #23578f), color-stop(100%, #2d70b8)); 
  background-image: -moz-linear-gradient(top, #94bbe5 0%, #4b8cd3 10%, 
# 265f9c 50%, #23578f 50%, #2d70b8 100%);

  background-image: linear-gradient(top, #94bbe5 0%, #4b8cd3 10%, 
# 265f9c 50%, #23578f 50%, #2d70b8 100%);

  border-color: #1a416b; 
  text-shadow: #002751 0px 1px 1px; 
  -moz-box-shadow: rgba(255, 255, 255, 0.41) 0 0 0.1em 1px inset; 
  -webkit-box-shadow: rgba(255, 255, 255, 0.41) 0 0 0.1em 1px inset; 
  -o-box-shadow: rgba(255, 255, 255, 0.41) 0 0 0.1em 1px inset; 
  box-shadow: rgba(255, 255, 255, 0.41) 0 0 0.1em 1px inset; 
  -moz-background-clip: padding; 
  -webkit-background-clip: padding; 
  -o-background-clip: padding-box; 
  -ms-background-clip: padding-box; 
  -khtml-background-clip: padding-box; 
  background-clip: padding-box;

**Comment by imathis** [comment]
Browser extensions don't validate as they are not valid CSS, they are browser vendor's proprietary implementations.
