### ISSUE TITLE
Undefined mixin fancy-button

### ISSUE THREAD

**Issue by kalabiyau** [imathis/fancy-buttons#24]
- compass (0.10.6)
- compass-colors (0.3.1)
- fancy-buttons (1.0.6)
- rails (3.0.4)

This is done:
# Add the following lines to your compass configuration file:

require 'fancy-buttons'
# Then run the following command:

compass install -r fancy-buttons -f fancy-buttons

in scss
.button { @include fancy-button;}

**Comment by travischoma** [comment]
Had the exact same versions and issue, restarted the rails server and it solved it.
