### ISSUE TITLE
Line 98: At least two color stops are required

### ISSUE THREAD

**Issue by bostonou** [imathis/fancy-buttons#25]
Hi,

I'm just trying out fancy-buttons and get the following error:

```
Sass::SyntaxError on line ["98"] of /compass/stylesheets/compass/css3/_gradient.scss: At least two color stops are required for a radial-gradient
  /compass/stylesheets/compass/css3/_gradient.scss:98:in radial-gradient'
  /app/stylesheets/buttons.scss:27:in `custom-fancy-gradient'
  /gems/fancy-buttons-1.1.0.alpha.1/lib/stylesheets/_fancy-buttons.sass:108:in `fb-state-colors'
  /gems/fancy-buttons-1.1.0.alpha.1/lib/stylesheets/_fancy-buttons.sass:88:in `fb-color'
  /gems/fancy-buttons-1.1.0.alpha.1/lib/stylesheets/_fancy-buttons.sass:30:in `fancy-button-colors'
  /gems/fancy-buttons-1.1.0.alpha.1/lib/stylesheets/_fancy-buttons.sass:74:in `fancy-button-colors-custom'
```

Any ideas what I'm doing wrong? I'm using haml-3.0.25, sass-3.1.0.alpha.252, compass-0.11.beta.5, and fancy-buttons-1.1.0.alpha.1.

I initially tried fancy-buttons 1.0.6 but I kept getting the error described [here (Syntax error: Not a valid color stop: #6a6a6a 10%)](https://github.com/imathis/fancy-buttons/issues/closed#issue/18)

**Comment by imathis** [comment]
Which version of Compass are you using? If you're on a Compass 0.11 beta, you'll want to use fancy-buttons 1.1.0.alpha.1 which you can install with `gem install fancy-buttons --pre`.
