### ISSUE TITLE
Customizing a gradient stop.

### ISSUE THREAD

**Issue by kidfribble** [imathis/fancy-buttons#28]
I would love to use this, but I'm not happy with the default gradient. Could you describe in some manner the format for customizing this? If you haven't built that in, can you estimate when you might or if you will? Thanks! Looks like a useful gem.

**Comment by imathis** [comment]
Right now there is a way you can customize the gradient, but isn't very sophisticated, and I wouldn't recommend it. I'm actually right in the polishing stage of a complete rewrite which focuses entirely on customization and variety. I'm going out and collecting the best CSS3 button styles from around the web and making them all available in fancy-buttons. There will be a growing list of supported styles, and you'd just write @include fancy-buttons($theme: itunes); and you'd get a nice blue "View in iTunes" style button. You won't even have to pick a color. If you'd like to change the color you can, and the button colors and gradients will be applied consistently for the style of that button.

Anyway, so yes the answer is: This is coming soon, and it's going to be awesome.
