### ISSUE TITLE
Making links and buttons look the same

### ISSUE THREAD

**Issue by ramontayag** [imathis/fancy-buttons#35]
I'm applying the same style to links and buttons. For example, let's say I have a link (`a` tag) to edit an item, and right beside it, an `input` button to delete that item. Even if I apply the same button, the edit link's padding is different from the delete button. It looks like this with `padding: 3px 10px`

http://grab.by/bfJL

Is this a browser/HTML issue? Or a fancy buttons issue?

**Comment by lawso017** [comment]
Make sure you're using the fancy-button-structure mixin:

fancy-button-structure($font-size: $fb-font-size, $radius: $fb-radius, $border-width: $fb-border-width, $line-height: $fb-line-height)

... and set the line-height property explicitly, as not all browsers will calculate a consistent line height between links and inputs.

**Comment by ramontayag** [comment]
Ohh.. that's great. Thanks @lawso017!
