### ISSUE TITLE
file to import not found or unreadable

### ISSUE THREAD

**Issue by pdewouters** [imathis/fancy-buttons#39]
Syntax error: File to import not found or unreadable: fancy-buttons.
              Load paths:
                F:/clients/localdev/wpdev/wp-content/themes/wpc-childtheme/sass
                C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.1/frameworks/blueprint/stylesheets
                C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.1/frameworks/compass/stylesheets
                C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-susy-plugin-0.9/sass
                Compass::SpriteImporter
        on line 1 of F:/clients/localdev/wpdev/wp-content/themes/wpc-childtheme/sass/buttons.scss

1: F:/clients/localdev/wpdev/wp-content/themes/wpc-childtheme/sass/buttons.scss

Config.rb has this
require 'fancy-buttons'

and buttons.scss
@import "fancy-buttons";

**Comment by imathis** [comment]
Did you run the install command? `compass install -r fancy-buttons -f fancy-buttons`

**Comment by pdewouters** [comment]
yes, it's an existing project.
do I have to add this in config.rb?
rails: compass.config, other: config.rb

**Comment by imathis** [comment]
It looks like it's not able to find the fancy-buttons gem. Perhaps you didn't install it? `gem install fancy-buttons` or something is wonky with your gem setup.

**Comment by pdewouters** [comment]
the gem is installed

**Comment by imathis** [comment]
Was it working before, or did you just try it for the first time? Honestly it seems like something isn't properly configured.

**Comment by pdewouters** [comment]
first time.
the source is here:
https://github.com/pdewouters/genesis-child-theme

**Comment by imathis** [comment]
I just checked out your code, uncommented the fancy-buttons stuff and I was able to compile it without any problems. Looks like this is an issue on your end.

**Comment by pdewouters** [comment]
thanks for that!
it's weird because I'm using other gems without issues.
I'll try re-installing

**Comment by pdewouters** [comment]
re-installing the gem did the trick
