### ISSUE TITLE
make button image url a variable

### ISSUE THREAD

**Issue by bridiver** [imathis/fancy-buttons#4]
It would be much easier to manage the location of the button graphic if it was a variable

!fb_button_image ||= #{image_url("button_bg.png")}

or something similar

**Comment by imathis** [comment]
Seems like a great idea, thanks. I'll put in the next version.

**Comment by imathis** [comment]
Ok I've done this in the latest version: !fb_image_path will allow you to set the path for the button's background image. It defaults to image_url("button_bg.png").

Thanks for the idea.

**Comment by seivan** [comment]
!fb_button_image ||= #{image_url("button_bg.png")}

Using ruby interpolation there doesn't seem to work... 
I keep getting   error src/buttons.sass (Line 153: Undefined variable: "!fb_bg_image_path".)

**Comment by imathis** [comment]
aww blast, thanks. I'll see what I can do.

**Comment by imathis** [comment]
I've just pushed 0.3.9 to gemcutter, this should fix the path issue. Sorry about that.

You'll want to set !fb_image_path not !fb_button_image. Let me know if this works how you expect it to.
