### ISSUE TITLE
The installation guide

### ISSUE THREAD

**Issue by seivan** [imathis/fancy-buttons#6]
I am doing an app template to work with fancy buttons and compass.

And I noticed in the installation guides it says

"# Then run the following command:
compass -r fancy-buttons -f fancy-buttons project_directory"

Is it supposed to say fancy-buttons twice, shouldn't one of them be compass-colors?

**Comment by imathis** [comment]
I've updated the installation guide, now it uses the compass 0.10 method. The reason that it is listed twice is that one is specifying the requirement (for the config file) and the second time is specifying that it should be installed as a framework. The second command is what puts the starter files in your library.
