### ISSUE TITLE
Do not want an additional stylesheet in my layout!

### ISSUE THREAD

**Issue by activestylus** [imathis/fancy-buttons#7]
Why make an additional http request just for button styles? I would much rather just be able to mix the goodies into my sass, the way other compass plugins work.

**Comment by imathis** [comment]
Fancy buttons doesn't require you to do this, it simply provides buttons.sass to give you an idea of how the plugin works and let you use it right away, copy it to another file, or delete it and start from scratch. The only thing you have to do to use fancy buttons is add "@import fancy_buttons" to the top of one of your sass files. For example, I have a _base.sass file where I handle all my plugin imports and that's where I import fancy_buttons.

**Comment by activestylus** [comment]
i was following the install instructions and didnt realize that step was optional - probably worth clarifying.

Thanks!
