### ISSUE TITLE
v-gradient removed in Compass pre7

### ISSUE THREAD

**Issue by AaronH** [imathis/fancy-buttons#9]
The v-gradient method has been removed in compass pre7 and replaced with an updated linear-gradient (via commit http://github.com/chriseppstein/compass/commit/aef52bd57e1a8ecc33a56ff4a74adb205658cd2f)

Not completely tested, but a quick fix is to replace the v-gradient lines in _fancy_gradient.sass as follows (in order):

<pre><code>
+linear-gradient(color_stops(!top_shine, !top_middle 10%, !middle 50%, !bottom_middle 50%, !bottom_glow))

+linear-gradient(color_stops(!top, !top_middle 30%, !middle 50%, !bottom_middle 50%, !bottom))

+linear-gradient(color_stops(!color1, !color2))

+linear-gradient(color_stops(!top, !middle 85%, !middle 40%, !bottom))
</code></pre>

**Comment by imathis** [comment]
Thanks, having worked with Chris to make the new gradient mixins I'm aware of this. I'll be releasing an updated version of Fancy Buttons soon.

**Comment by sbader** [comment]
Thanks for this. Helped me out a lot.

**Comment by imathis** [comment]
I've just pushed the latest Fancy Buttons 0.4.0 to gem cutter, you should be able to install it now. It requires Compass 0.10.0.pre8 which was released earlier today. Let me know if you run into any problems.

**Comment by AaronH** [comment]
So far so good.  Thanks.
